services:
  shopper:
    build: .
    container_name: shopper
    restart: always
    ports:
      - 3333:3333
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://shopper:shopper@shopper-db:5432/shopper
      GEMINI_API_KEY: ${GEMINI_API_KEY}
  postgres:
    image: postgres:16.3-alpine3.20
    container_name: shopper-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: shopper
      POSTGRES_PASSWORD: shopper

  nginx:
    image: nginx:alpine
    container_name: shopper-nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - postgres
